#!/sbin/openrc-run

name=$RC_SVCNAME
description="Sidera Core service"
supervisor="supervise-daemon"
command="/usr/bin/sidera"
extra_commands="checkconfig"
extra_started_commands="reload"

: ${SIDERA_CONFIG:=${config:-"/etc/sidera"}}

if [ -d "$SIDERA_CONFIG" ]; then
	_config_opt="-C $SIDERA_CONFIG"
elif [ -z "$SIDERA_CONFIG" ]; then
	_config_opt=""
else
	_config_opt="-c $SIDERA_CONFIG"
fi

_workdir=${SIDERA_WORKDIR:-${workdir:-"/var/lib/sidera"}}
_runtime_config=${SIDERA_RUNTIME_CONFIG:-"$_workdir/runtime.json"}

command_args="run --disable-color
	-D $_workdir
	--runtime-config $_runtime_config
	$_config_opt"

depend() {
	after net dns
}

checkconfig() {
	ebegin "Checking $RC_SVCNAME configuration"
	sidera check -D "$_workdir" --runtime-config "$_runtime_config" $_config_opt
	eend $?
}

start_pre() {
	checkconfig
}

reload() {
	ebegin "Reloading $RC_SVCNAME"
	checkconfig && $supervisor "$RC_SVCNAME" --signal HUP
	eend $?
}
