// Code generated by 'go generate'; DO NOT EDIT.

package main

import (
	"syscall"
	"unsafe"

	"golang.org/x/sys/windows"
)

var _ unsafe.Pointer

// Do the interface allocations only once for common
// Errno values.
const (
	errnoERROR_IO_PENDING = 997
)

var (
	errERROR_IO_PENDING error = syscall.Errno(errnoERROR_IO_PENDING)
	errERROR_EINVAL     error = syscall.EINVAL
)

// errnoErr returns common boxed Errno values, to prevent
// allocations at runtime.
func errnoErr(e syscall.Errno) error {
	switch e {
	case 0:
		return errERROR_EINVAL
	case errnoERROR_IO_PENDING:
		return errERROR_IO_PENDING
	}
	// TODO: add more here, after collecting data on the common
	// error values see on Windows. (perhaps when running
	// all.bat?)
	return e
}

var (
	modwintrust = windows.NewLazySystemDLL("wintrust.dll")

	procWTHelperGetProvCertFromChain   = modwintrust.NewProc("WTHelperGetProvCertFromChain")
	procWTHelperGetProvSignerFromChain = modwintrust.NewProc("WTHelperGetProvSignerFromChain")
	procWTHelperProvDataFromStateData  = modwintrust.NewProc("WTHelperProvDataFromStateData")
)

func winTrustProviderCertificateFromChain(providerSigner uintptr, certificateIndex uint32) (providerCertificate uintptr) {
	r0, _, _ := syscall.SyscallN(procWTHelperGetProvCertFromChain.Addr(), uintptr(providerSigner), uintptr(certificateIndex))
	providerCertificate = uintptr(r0)
	return
}

func winTrustProviderSignerFromChain(providerData uintptr, signerIndex uint32, counterSigner uint32, counterSignerIndex uint32) (providerSigner uintptr) {
	r0, _, _ := syscall.SyscallN(procWTHelperGetProvSignerFromChain.Addr(), uintptr(providerData), uintptr(signerIndex), uintptr(counterSigner), uintptr(counterSignerIndex))
	providerSigner = uintptr(r0)
	return
}

func winTrustProviderDataFromStateData(stateData windows.Handle) (providerData uintptr) {
	r0, _, _ := syscall.SyscallN(procWTHelperProvDataFromStateData.Addr(), uintptr(stateData))
	providerData = uintptr(r0)
	return
}
